language: ruby
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=spinach_project DB=mysql
    - TASK=spinach_other DB=mysql
    - TASK=spec:api DB=mysql
    - TASK=spec:feature DB=mysql
    - TASK=spec:other DB=mysql
    - TASK=jasmine:ci DB=mysql
    - TASK=spinach_project DB=postgresql
    - TASK=spinach_other DB=postgresql
    - TASK=spec:api DB=postgresql
    - TASK=spec:feature DB=postgresql
    - TASK=spec:other DB=postgresql
    - TASK=jasmine:ci DB=postgresql
before_install:
  - sudo apt-get install libicu-dev -y
install: 
  - "bundle install --deployment --without production"
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
services:
  - redis-server
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
notifications:
  email: false
